Import-Package instead of Require-Bundle for javax and log4j
eclipse-passage/passage pull request #1121
Opened 2022-09-19 11:22 UTC by HannesWell

Using Import-Package instead of Require-Bundle to specify dependencies in a Manifest.Mf is a general recommendation for OSGi.
It is especially useful for packages like javax.* or log4j that can have multiple provides (e.g. the traditional javax vs jakarta or other bundles that repackage them) from different sources (for example Eclipse-Orbit vs. Maven-Central).

Therefore this PR replaces all Require-Bundle directives for javax and log4j bundles by corresponding Package-Imports.

2022-09-19 16:02 UTC, HannesWell commented
@ruspl-afed it looks like the preparation for the 2.6 is not yet done. Let me know if I should rebase this change after it has been completed.

2022-09-20 16:28 UTC, HannesWell commented
Requiring the bundle `org.apache.logging.log4j` also has the effect that Passage pulls in the full log4j logging framework into each application that uses passage. This is problematic if another logging framework implementation like logback is actually intended to be used because then two logging implementations are present.
If a bundle is only programmed against the log4j api and only imports the api packages (as suggested with this PR) a corresponding bridge/connector can be used in an application to redirect the logger output for example to logback.

2022-10-03 19:10 UTC, ruspl-afed commented
Dear @HannesWell,  we need these trivial pom.xml files to assembly our bundles for Maven Central. 

In any case I would avoid mixing of these changes with javax and log4j -related changes

2022-10-03 19:12 UTC, ruspl-afed requested changes
Please do not mix pom.xml removing with switching to Import-Package directive

2022-10-03 19:38 UTC, HannesWell commented
> Dear @HannesWell, we need these trivial pom.xml files to assembly our bundles for Maven Central.
> 
> In any case I would avoid mixing of these changes with javax and log4j -related changes

Understand, I removed the commit about the poms and only left the ones about the javax/log4j changes.

2022-10-03 20:04 UTC, ruspl-afed approved these changes
ok, let's try it

2022-10-03 20:04 UTC, merged

2022-10-03 20:17 UTC, HannesWell commented
Thank you.